name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Or 'zulu', 'adopt', 'microsoft', etc.
        cache: 'maven' # Or 'gradle', 'sbt' if applicable for caching dependencies
    - name: Build with Maven
      run: mvn clean install
