name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Onboardbase
        run: wget https://onboardbase-cli.fra1.digitaloceanspaces.com/apt/onboardbase.deb
      - name: Install Onboardbase
        run: sudo dpkg -i onboardbase.deb
      - name: Setup Onboardbase
        run: onboardbase config:set --token "${{ secrets.ONBOARDBASE_TOKEN }}"
      - name: Run project
        run: onboardbase build -c "printenv SECRET_ENV_VARIABLE" --project "github actions test" -e "development"
